=== the6wheels/Bases-de-donnees-Avances-II-TP-04/Activites.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT Activites (sport+,personne+,club+,moniteur+,pratique+)>
<!ATTLIST Activites
  xmlns CDATA #FIXED ''>

<!ELEMENT sport (categorie)>
<!ATTLIST sport
  xmlns CDATA #FIXED ''
  nom NMTOKEN #REQUIRED>

<!ELEMENT personne (nom,adresse)>
<!ATTLIST personne
  xmlns CDATA #FIXED ''
  ident NMTOKEN #REQUIRED>

<!ELEMENT club EMPTY>
<!ATTLIST club
  xmlns CDATA #FIXED ''
  ident NMTOKEN #REQUIRED
  nom NMTOKEN #REQUIRED>

<!ELEMENT moniteur EMPTY>
<!ATTLIST moniteur
  xmlns CDATA #FIXED ''
  club NMTOKEN #REQUIRED
  ident NMTOKEN #REQUIRED
  nom NMTOKEN #REQUIRED>

<!ELEMENT pratique (choixsports+,annee)>
<!ATTLIST pratique
  xmlns CDATA #FIXED ''
  ident NMTOKEN #REQUIRED
  moniteur NMTOKEN #REQUIRED
  personne NMTOKEN #REQUIRED>

<!ELEMENT categorie (#PCDATA)>
<!ATTLIST categorie
  xmlns CDATA #FIXED ''>

<!ELEMENT nom (#PCDATA)>
<!ATTLIST nom
  xmlns CDATA #FIXED ''>

<!ELEMENT adresse (#PCDATA)>
<!ATTLIST adresse
  xmlns CDATA #FIXED ''>

<!ELEMENT choixsports EMPTY>
<!ATTLIST choixsports
  xmlns CDATA #FIXED ''
  duree CDATA #REQUIRED
  sport NMTOKEN #REQUIRED>

<!ELEMENT annee (#PCDATA)>
<!ATTLIST annee
  xmlns CDATA #FIXED ''>

=== the6wheels/Bases-de-donnees-Avances-II-TP-04/lesActivites.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Activites SYSTEM "Activites.dtd">
<Activites>
    <sport nom="S1">
        <categorie>G1</categorie>
    </sport>
    <sport nom="S2">
        <categorie>G2</categorie>
    </sport>
    <sport nom="S3">
        <categorie>G3</categorie>
    </sport>
    <personne ident="P1">
        <nom>Ali</nom>
        <adresse>SBA</adresse>
    </personne>
    <personne ident="P2">
        <nom>AMEL</nom>
        <adresse>alger</adresse>
    </personne>
    <personne ident="P3">
        <nom>Omar</nom>
        <adresse>Oran</adresse>
    </personne>
    <club ident="C1" nom="club1"/>
    <club ident="C2" nom="club2"/>
    <moniteur ident="M1" nom="Amine" club="C1"/>
    <moniteur ident="M2" nom="Ahmed" club="C2"/>
    <moniteur ident="M3" nom="Mohamed" club="C1"/>
    <pratique ident="R1" moniteur="M1" personne="P1">
        <choixsports sport="S1" duree="4"/>
        <annee>2017</annee>
    </pratique>
    <pratique ident="R2" moniteur="M2" personne="P2">
        <choixsports sport="S2" duree="6"/>
        <annee>2017</annee>
    </pratique>
    <pratique ident="R3" moniteur="M1" personne="P1">
        <choixsports sport="S3" duree="4"/>
        <choixsports sport="S2" duree="4"/>
        <annee>2018</annee>
    </pratique>
</Activites>
